### ISSUE TITLE
NoClassDefFoundError: reactor/core/scheduler/Schedulers

### ISSUE THREAD

**Issue by bobbyfu** [mokies/ratelimitj#10]
I have the following dependencies in the gradle file. 

dependencies {
    . . . 
    // 'ratelimitj-redis-0.4.1.jar'
    compile ('io.projectreactor:reactor-core:3.1.2.RELEASE')
    compile ('es.moki.ratelimitj:ratelimitj-redis:0.4.1')
   . . . 
}
The first line throws me an NoClassDefFoundError.   Any idea to workaround this? 

RedisClient client = RedisClient.create(RedisURI.create("localhost", 6379));

Caused by: java.lang.NoClassDefFoundError: reactor/core/scheduler/Schedulers
	at io.lettuce.core.resource.DefaultClientResources.<init>(DefaultClientResources.java:171)
	at io.lettuce.core.resource.DefaultClientResources$Builder.build(DefaultClientResources.java:461)
	at io.lettuce.core.resource.DefaultClientResources.create(DefaultClientResources.java:229)
	at io.lettuce.core.AbstractRedisClient.<init>(AbstractRedisClient.java:96)
	at io.lettuce.core.RedisClient.<init>(RedisClient.java:86)
	at io.lettuce.core.RedisClient.create(RedisClient.java:123)
	at io.squelch.collector.api.controller.OAuthController.health(OAuthController.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)

**Comment by bobbyfu** [comment]
I found the issue.  I have multiple version of the io.projectreactor:reactor-core libraries in the classpath.  Removed the older version of the reactor-core dependency fixed the problem.
